from schemas import UserCreate, UserUpdate
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func
from models import User
from uuid import UUID
from typing import List, Optional

class UserRepository:
    async def get_by_id(self, session, user_id: UUID) -> User | None: ...
    async def get_by_filter(self, session, count: int, page: int, **kwargs) -> list[User]: ...
    async def create(self, session, user_data: UserCreate) -> User: ...
    async def update(self, session, user_id: UUID, user_data: UserUpdate) -> User: ...
    async def delete(self, session, user_id: UUID) -> None: ...
    async def count(self) -> int:
        result = await self.session.execute(select(func.count(User.id)))
        return result.scalar_one()